BEGIN_FUNCTION_MAP
	.Func,예상지수(t1485),t1485,attr,block,headtype=A;
	BEGIN_DATA_MAP
	t1485InBlock,기본입력,input;
	begin
		업종코드,upcode,upcode,char,3;
		조회구분,gubun,gubun,char,1;
	end
	t1485OutBlock,출력,output;
	begin
		현재지수,pricejisu,pricejisu,float,10.2;
		지수전일대비구분,sign,sign,char,1;
		전일대비,change,change,float,10.2;
		거래량,volume,volume,long,12;
		상승종목수,yhighjo,yhighjo,long,4;
		상한종목수,yupjo,yupjo,long,4;
		보합종목수,yunchgjo,yunchgjo,long,4;
		하락종목수,ylowjo,ylowjo,long,4;
		하한종목수,ydownjo,ydownjo,long,4;
		거래형성수,ytrajo,ytrajo,long,4;
	end
	t1485OutBlock1,출력1,output,occurs;
	begin
		시간,chetime,chetime,char,6;
		예상지수,jisu,jisu,float,10.2;
		전일대비구분,sign,sign,char,1;
		전일대비,change,change,float,10.2;
		예상체결량,volume,volume,long,12;
		예상체결량직전대비,volcha,volcha,long,12;
	end
	END_DATA_MAP
END_FUNCTION_MAP

