BEGIN_FUNCTION_MAP
	.Func,업종현재가(t1511),t1511,attr,block,headtype=A;
	BEGIN_DATA_MAP
	t1511InBlock,기본입력,input;
	begin
		업종코드,upcode,upcode,char,3;
	end
	t1511OutBlock,기본출력,output;
	begin
		업종구분,gubun,gubun,char,1;
		업종명,hname,hname,char,20;
		현재지수,pricejisu,pricejisu,float,7.2;
		전일지수,jniljisu,jniljisu,float,7.2;
		전일대비구분,sign,sign,char,1;
		전일대비,change,change,float,7.2;
		지수등락율,diffjisu,diffjisu,float,6.2;
		전일거래량,jnilvolume,jnilvolume,long,12;
		당일거래량,volume,volume,long,12;
		거래량전일대비,volumechange,volumechange,long,12;
		거래량비율,volumerate,volumerate,float,6.2;
		전일거래대금,jnilvalue,jnilvalue,long,12;
		당일거래대금,value,value,long,12;
		거래대금전일대비,valuechange,valuechange,long,12;
		거래대금비율,valuerate,valuerate,float,6.2;
		시가지수,openjisu,openjisu,float,7.2;
		시가등락율,opendiff,opendiff,float,6.2;
		시가시간,opentime,opentime,char,6;
		고가지수,highjisu,highjisu,float,7.2;
		고가등락율,highdiff,highdiff,float,6.2;
		고가시간,hightime,hightime,char,6;
		저가지수,lowjisu,lowjisu,float,7.2;
		저가등락율,lowdiff,lowdiff,float,6.2;
		저가시간,lowtime,lowtime,char,6;
		52주최고지수,whjisu,whjisu,float,7.2;
		52주최고현재가대비,whchange,whchange,float,7.2;
		52주최고지수일자,whjday,whjday,char,8;
		52주최저지수,wljisu,wljisu,float,7.2;
		52주최저현재가대비,wlchange,wlchange,float,7.2;
		52주최저지수일자,wljday,wljday,char,8;
		연중최고지수,yhjisu,yhjisu,float,7.2;
		연중최고현재가대비,yhchange,yhchange,float,7.2;
		연중최고지수일자,yhjday,yhjday,char,8;
		연중최저지수,yljisu,yljisu,float,7.2;
		연중최저현재가대비,ylchange,ylchange,float,7.2;
		연중최저지수일자,yljday,yljday,char,8;
		첫번째지수코드,firstjcode,firstjcode,char,3;
		첫번째지수명,firstjname,firstjname,char,20;
		첫번째지수,firstjisu,firstjisu,float,7.2;
		첫번째대비구분,firsign,firsign,char,1;
		첫번째전일대비,firchange,firchange,float,7.2;
		첫번째등락율,firdiff,firdiff,float,6.2;
		두번째지수코드,secondjcode,secondjcode,char,3;
		두번째지수명,secondjname,secondjname,char,20;
		두번째지수,secondjisu,secondjisu,float,7.2;
		두번째대비구분,secsign,secsign,char,1;
		두번째전일대비,secchange,secchange,float,7.2;
		두번째등락율,secdiff,secdiff,float,6.2;
		세번째지수코드,thirdjcode,thirdjcode,char,3;
		세번째지수명,thirdjname,thirdjname,char,20;
		세번째지수,thirdjisu,thirdjisu,float,7.2;
		세번째대비구분,thrsign,thrsign,char,1;
		세번째전일대비,thrchange,thrchange,float,7.2;
		세번째등락율,thrdiff,thrdiff,float,6.2;
		네번째지수코드,fourthjcode,fourthjcode,char,3;
		네번째지수명,fourthjname,fourthjname,char,20;
		네번째지수,fourthjisu,fourthjisu,float,7.2;
		네번째대비구분,forsign,forsign,char,1;
		네번째전일대비,forchange,forchange,float,7.2;
		네번째등락율,fordiff,fordiff,float,6.2;
		상승종목수,highjo,highjo,long,4;
		상한종목수,upjo,upjo,long,4;
		보합종목수,unchgjo,unchgjo,long,4;
		하락종목수,lowjo,lowjo,long,4;
		하한종목수,downjo,downjo,long,4;
	end
	END_DATA_MAP
END_FUNCTION_MAP

