BEGIN_FUNCTION_MAP
	.Func,ELW지표검색(t1955),t1955,attr,block,headtype=A;
	BEGIN_DATA_MAP
	t1955InBlock,입력,input;
	begin
		기초자산chk구분,chkitem,chkitem,char,1;
		기초자산코드,cbitem,cbitem,char,12;
		발행사chk구분,chkissuer,chkissuer,char,1;
		발행사,cbissuer,cbissuer,char,12;
		권리chk구분,chkcallput,chkcallput,char,1;
		권리(call:01.put:02),cbcallput,cbcallput,char,2;
		행사가chk구분,chkexec,chkexec,char,1;
		행사가(>=:1.<=:2),cbexec,cbexec,char,1;
		행사방식chk구분,chktype,chktype,char,1;
		행사방식,cbtype,cbtype,char,2;
		결제방법chk구분,chksettle,chksettle,char,1;
		결제방법,cbsettle,cbsettle,char,2;
		만기chk구분,chklast,chklast,char,1;
		만기월별,cblast,cblast,char,6;
		행사가격chk구분,chkelwexec,chkelwexec,char,1;
		행사가이상,elwexecs,elwexecs,float,10.2;
		행사가이하,elwexece,elwexece,float,10.2;
		거래량chk구분,chkvolume,chkvolume,char,1;
		거래량이상,volumes,volumes,float,12;
		거래량이하,volumee,volumee,float,12;
		등락율chk구분,chkrate,chkrate,char,1;
		등락율이상,rates,rates,float,6.2;
		등락율이하,ratee,ratee,float,6.2;
		프리미엄chk구분,chkpremium,chkpremium,char,1;
		프리미엄이상,premiums,premiums,float,6.2;
		프리미엄이하,premiume,premiume,float,6.2;
		패리티chk구분,chkparity,chkparity,char,1;
		패리티이상,paritys,paritys,float,6.2;
		패리티이하,paritye,paritye,float,6.2;
		손익분기chk구분,chkberate,chkberate,char,1;
		손익분기이상,berates,berates,float,6.2;
		손익분기이하,beratee,beratee,float,6.2;
		자본지지chk구분,chkcapt,chkcapt,char,1;
		자본지지이상,capts,capts,float,6.2;
		자본지지이하,capte,capte,float,6.2;
		e.기어링chk구분,chkegearing,chkegearing,char,1;
		e.기어링이상,egearings,egearings,float,6.2;
		e.기어링이하,egearinge,egearinge,float,6.2;
		기어링chk구분,chkgearing,chkgearing,char,1;
		기어링이상,gearings,gearings,float,6.2;
		기어링이하,gearinge,gearinge,float,6.2;
		델타chk구분,chkdelta,chkdelta,char,1;
		델타이상,deltas,deltas,float,10.6;
		델타이하,deltae,deltae,float,10.6;
		쎄타chk구분,chktheta,chktheta,char,1;
		쎄타이상,thetas,thetas,float,10.6;
		쎄타이하,thetae,thetae,float,10.6;
		최종거래일chk구분,chkduedate,chkduedate,char,1;
		최종거래일이상,duedates,duedates,char,8;
		최종거래일이하,duedatee,duedatee,char,8;
		조기종료chk구분,chkkoba,chkkoba,char,1;
		조기종료(0:전체1:조기종료만2:조기종료제외),cbkoba,cbkoba,char,1;
	end
	t1955OutBlock,출력,output;
	begin
		종목갯수,cnt,cnt,long,4;
	end
	t1955OutBlock1,출력1,output,occurs;
	begin
		종목명,hname,hname,char,40;
		종목코드,shcode,shcode,char,6;
		발행사,issuernmk,issuernmk,char,40;
		기초자산코드,itemcode,itemcode,char,12;
		콜/풋구분,cpgubun,cpgubun,char,2;
		현재가,price,price,long,8;
		전일대비구분,sign,sign,char,1;
		전일대비,change,change,long,8;
		등락율,diff,diff,float,6.2;
		거래량,volume,volume,float,12;
		전일거래량,jnilvolume,jnilvolume,float,12;
		행사가,elwexec,elwexec,float,10.2;
		기초자산명,item,item,char,20;
		기초자산가,bprice,bprice,float,10.2;
		기초전일대비구분,bsign,bsign,char,1;
		기초전일대비,bchange,bchange,float,10.2;
		기초등락율,bdiff,bdiff,float,6.2;
		프리미엄,premium,premium,float,6.2;
		패리티,parity,parity,float,6.2;
		손익분기,berate,berate,float,6.2;
		자본지지,capt,capt,float,6.2;
		e.기어링,egearing,egearing,float,6.2;
		기어링,gearing,gearing,float,6.2;
		최종거래일,lastdate,lastdate,char,8;
		델타,delta,delta,float,10.6;
		쎄타,theta,theta,float,10.6;
	end
	END_DATA_MAP
END_FUNCTION_MAP

t1955