BEGIN_FUNCTION_MAP
	.Func,ELW전광판(t1964),t1964,attr,block,headtype=A;
	BEGIN_DATA_MAP
	t1964InBlock,기본입력,input;
	begin
		기초자산코드,item,item,char,12;
		발행사,issuercd,issuercd,char,12;
		만기월물,lastmonth,lastmonth,char,6;
		콜풋구분,elwopt,elwopt,char,1;
		머니구분,atmgubun,atmgubun,char,1;
		권리행사방식,elwtype,elwtype,char,2;
		결제방법,settletype,settletype,char,2;
		행사기초자산구분,elwexecgubun,elwexecgubun,char,1;
		시작비율,fromrat,fromrat,char,5;
		종료비율,torat,torat,char,5;
		거래량,volume,volume,char,12;
	end
	t1964OutBlock1,출력1,output,occurs;
	begin
		ELW코드,shcode,shcode,char,6;
		종목명,hname,hname,char,40;
		기초자산코드,item1,item1,char,6;
		기초자산명,itemnm,itemnm,char,20;
		발행사,issuernmk,issuernmk,char,40;
		콜풋구분,elwopt,elwopt,char,4;
		현재가,price,price,long,8;
		전일대비구분,sign,sign,char,1;
		전일대비,change,change,long,8;
		등락율,diff,diff,float,6.2;
		거래량,volume,volume,long,12;
		행사가,elwexec,elwexec,float,10.2;
		잔존일수,jandatecnt,jandatecnt,long,8;
		전환비율,convrate,convrate,float,8.4;
		최종거래일,lastdate,lastdate,char,8;
		행사개시일,mmsdate,mmsdate,char,8;
		지급일,payday,payday,char,8;
		발행수량,listing,listing,long,8;
		머니구분,atmgbnm,atmgbnm,char,10;
		패리티,parity,parity,float,6.2;
		프리미엄,preminum,preminum,float,10.2;
		스프래드,spread,spread,float,3.2;
		손익분기율,berate,berate,float,6.2;
		자본지지율,capt,capt,float,6.2;
		기어링,gearing,gearing,float,6.2;
		e기어링,egearing,egearing,float,6.2;
		기초자산현재가,itemprice,itemprice,long,8;
		기초자산전일대비구분,itemsign,itemsign,char,1;
		기초자산전일대비,itemchange,itemchange,long,8;
		기초자산등락율,itemdiff,itemdiff,float,6.2;
		기초자산거래량,itemvolume,itemvolume,long,12;
		전일거래량,jnilvolume,jnilvolume,long,12;
		이론가,theoryprice,theoryprice,float,10.2;
		LP보유비율,lp_rate,lp_rate,float,5.2;
		내재변동성,impv,impv,float,6.2;
		델타,delta,delta,float,10.6;
		쎄타,theta,theta,float,10.6;
	end
	END_DATA_MAP
END_FUNCTION_MAP

t1964