BEGIN_FUNCTION_MAP
	.Func,ELW종목비교(t1958),t1958,attr,block,headtype=A;
	BEGIN_DATA_MAP
	t1958InBlock,입력,input;
	begin
		종목코드1,shcode1,shcode1,char,6;
		종목코드2,shcode2,shcode2,char,6;
	end
	t1958OutBlock,출력,output;
	begin
		종목명,hname,hname,char,40;
		기초자산,item1,item1,char,12;
		발행사,issuernmk,issuernmk,char,40;
		콜풋구분,elwopt,elwopt,char,2;
		행사방식,elwtype,elwtype,char,2;
		결제방법,settletype,settletype,char,2;
		행사가,elwexec,elwexec,float,8.2;
		전환비율,convrate,convrate,float,12.4;
		발행수량,listing,listing,float,12;
		행사개시일,mmsdate,mmsdate,char,8;
		최종거래일,lastdate,lastdate,char,8;
		거래잔존일수,nofdays,nofdays,long,4;
		지급일,payday,payday,char,8;
		패리티,parity,parity,float,6.2;
		프리미엄,premium,premium,float,6.2;
		손익분기,berate,berate,float,6.2;
		자본지지,capt,capt,float,6.2;
		기어링,gearing,gearing,float,6.2;
		e.기어링,egearing,egearing,float,6.2;
		가격,price,price,long,8;
		거래량,volume,volume,float,12;
		등락율,diff,diff,float,6.2;
	end
	t1958OutBlock1,출력1,output;
	begin
		종목명,hname,hname,char,40;
		기초자산,item1,item1,char,12;
		발행사,issuernmk,issuernmk,char,40;
		콜풋구분,elwopt,elwopt,char,2;
		행사방식,elwtype,elwtype,char,2;
		결제방법,settletype,settletype,char,2;
		행사가,elwexec,elwexec,float,8.2;
		전환비율,convrate,convrate,float,12.4;
		발행수량,listing,listing,float,12;
		행사개시일,mmsdate,mmsdate,char,8;
		최종거래일,lastdate,lastdate,char,8;
		거래잔존일수,nofdays,nofdays,long,4;
		지급일,payday,payday,char,8;
		패리티,parity,parity,float,6.2;
		프리미엄,premium,premium,float,6.2;
		손익분기,berate,berate,float,6.2;
		자본지지,capt,capt,float,6.2;
		기어링,gearing,gearing,float,6.2;
		e.기어링,egearing,egearing,float,6.2;
		가격,price,price,long,8;
		거래량,volume,volume,float,12;
		등락율,diff,diff,float,6.2;
	end
	t1958OutBlock2,출력2,output;
	begin
		종목명비교,hnamecmp,hnamecmp,char,6;
		기초자산비교,item1cmp,item1cmp,char,6;
		발행사비교,issuernmkcmp,issuernmkcmp,char,6;
		콜풋구분비교,elwoptcmp,elwoptcmp,char,6;
		행사방식비교,elwtypecmp,elwtypecmp,char,6;
		결제방법비교,settlecmp,settlecmp,char,6;
		행사가비교,elwexeccmp,elwexeccmp,float,8.2;
		전환비율비교,convcmp,convcmp,float,12.4;
		발행수량비교,listingcmp,listingcmp,float,12;
		행사개시일비교,mmsdatecmp,mmsdatecmp,char,6;
		최종거래일비교,lastdatecmp,lastdatecmp,char,6;
		거래잔존일수비교,nofdayscmp,nofdayscmp,char,6;
		지급일비교,paydaycmp,paydaycmp,char,6;
		패리티비교,paritycmp,paritycmp,float,6.2;
		프리미엄비교,premiumcmp,premiumcmp,float,6.2;
		손익분기비교,beratecmp,beratecmp,float,6.2;
		자본지지비교,captcmp,captcmp,float,6.2;
		기어링비교,gearingcmp,gearingcmp,float,6.2;
		e.기어링비교,egearingcmp,egearingcmp,float,6.2;
		가격비교,pricecmp,pricecmp,long,8;
		거래량비교,volumecmp,volumecmp,float,12;
		등락율비교,diffcmp,diffcmp,float,6.2;
	end
	END_DATA_MAP
END_FUNCTION_MAP

t1958