BEGIN_FUNCTION_MAP
	.Func,상품선물투자자매매동향(챠트용),t2545,attr,block,headtype=A;
	BEGIN_DATA_MAP
	t2545InBlock,기본입력,input;
	begin
		상품ID,eitem,eitem,char,2;
		시장구분,sgubun,sgubun,char,1;
		업종코드,upcode,upcode,char,3;
		N분,nmin,nmin,int,2;
		조회건수,cnt,cnt,int,3;
		전일분,bgubun,bgubun,char,1;
	end
	t2545OutBlock,기본출력,output;
	begin
		상품ID,eitem,eitem,char,2;
		시장구분,sgubun,sgubun,char,1;
		개인투자자코드,indcode,indcode,char,4;
		외국인투자자코드,forcode,forcode,char,4;
		기관계투자자코드,syscode,syscode,char,4;
		증권투자자코드,stocode,stocode,char,4;
		투신투자자코드,invcode,invcode,char,4;
		은행투자자코드,bancode,bancode,char,4;
		보험투자자코드,inscode,inscode,char,4;
		종금투자자코드,fincode,fincode,char,4;
		기금투자자코드,moncode,moncode,char,4;
		기타투자자코드,etccode,etccode,char,4;
		국가투자자코드,natcode,natcode,char,4;
		사모펀드투자자코드,pefcode,pefcode,char,4;
		기준지수코드,jisucd,jisucd,char,8;
		기준지수명,jisunm,jisunm,char,20;
	end
	t2545OutBlock1,출력1,output,occurs;
	begin
		일자,date,date,char,8;
		시간,time,time,char,6;
		일자시간,datetime,datetime,char,14;
		개인순매수거래량,indmsvol,indmsvol,long,8;
		개인순매수거래대금,indmsamt,indmsamt,double,12.0;
		외국인순매수거래량,formsvol,formsvol,long,8;
		외국인순매수거래대금,formsamt,formsamt,double,12.0;
		기관계순매수거래량,sysmsvol,sysmsvol,long,8;
		기관계순매수거래대금,sysmsamt,sysmsamt,double,12.0;
		증권순매수거래량,stomsvol,stomsvol,long,8;
		증권순매수거래대금,stomsamt,stomsamt,double,12.0;
		투신순매수거래량,invmsvol,invmsvol,long,8;
		투신순매수거래대금,invmsamt,invmsamt,double,12.0;
		은행순매수거래량,banmsvol,banmsvol,long,8;
		은행순매수거래대금,banmsamt,banmsamt,double,12.0;
		보험순매수거래량,insmsvol,insmsvol,long,8;
		보험순매수거래대금,insmsamt,insmsamt,double,12.0;
		종금순매수거래량,finmsvol,finmsvol,long,8;
		종금순매수거래대금,finmsamt,finmsamt,double,12.0;
		기금순매수거래량,monmsvol,monmsvol,long,8;
		기금순매수거래대금,monmsamt,monmsamt,double,12.0;
		기타순매수거래량,etcmsvol,etcmsvol,long,8;
		기타순매수거래대금,etcmsamt,etcmsamt,double,12.0;
		국가순매수거래량,natmsvol,natmsvol,long,8;
		국가순매수거래대금,natmsamt,natmsamt,double,12.0;
		사모펀드순매수거래량,pefmsvol,pefmsvol,long,8;
		사모펀드순매수거래대금,pefmsamt,pefmsamt,double,12.0;
		기준지수,upclose,upclose,float,6.2;
		기준체결거래량,upcvolume,upcvolume,long,8;
		기준누적거래량,upvolume,upvolume,double,12.0;
		기준거래대금,upvalue,upvalue,double,12.0;
	end
	END_DATA_MAP
END_FUNCTION_MAP

