BEGIN_FUNCTION_MAP
	.Func,주식선물현재가조회(API용)(t8402),t8402,attr,block,headtype=A;
	BEGIN_DATA_MAP
	t8402InBlock,기본입력,input;
	begin
		단축코드,focode,focode,char,8;
	end
	t8402OutBlock,출력,output;
	begin
		한글명,hname,hname,char,20;
		현재가,price,price,long,8;
		전일대비구분,sign,sign,char,1;
		전일대비,change,change,long,8;
		전일종가,jnilclose,jnilclose,long,8;
		등락율,diff,diff,float,6.2;
		거래량,volume,volume,long,12;
		거래량전일동시간비율,stimeqrt,stimeqrt,double,6.2;
		거래대금,value,value,long,12;
		미결제량,mgjv,mgjv,long,8;
		미결제증감,mgjvdiff,mgjvdiff,long,8;
		시가,open,open,long,8;
		고가,high,high,long,8;
		저가,low,low,long,8;
		상한가,uplmtprice,uplmtprice,long,8;
		하한가,dnlmtprice,dnlmtprice,long,8;
		52최고가,high52w,high52w,long,8;
		52최저가,low52w,low52w,long,8;
		베이시스,basis,basis,float,6.2;
		기준가,recprice,recprice,long,8;
		이론가,theoryprice,theoryprice,long,8;
		괴리율,glyl,glyl,float,6.3;
		만기일,lastmonth,lastmonth,char,8;
		잔여일,jandatecnt,jandatecnt,long,8;
		종합지수,pricejisu,pricejisu,float,6.2;
		종합지수전일대비구분,jisusign,jisusign,char,1;
		종합지수전일대비,jisuchange,jisuchange,float,6.2;
		종합지수등락율,jisudiff,jisudiff,float,6.2;
		KOSPI200지수,kospijisu,kospijisu,float,6.2;
		KOSPI200전일대비구분,kospisign,kospisign,char,1;
		KOSPI200전일대비,kospichange,kospichange,float,6.2;
		KOSPI200등락율,kospidiff,kospidiff,float,6.2;
		상장최고가,listhprice,listhprice,long,8;
		상장최저가,listlprice,listlprice,long,8;
		델타,delt,delt,float,6.4;
		감마,gama,gama,float,6.4;
		세타,ceta,ceta,float,6.4;
		베가,vega,vega,float,6.4;
		로우,rhox,rhox,float,6.4;
		근월물현재가,gmprice,gmprice,long,8;
		근월물전일대비구분,gmsign,gmsign,char,1;
		근월물전일대비,gmchange,gmchange,long,8;
		근월물등락율,gmdiff,gmdiff,float,6.2;
		이론가,theorypriceg,theorypriceg,long,8;
		역사적변동성,histimpv,histimpv,float,6.2;
		내재변동성,impv,impv,float,6.2;
		시장BASIS,sbasis,sbasis,long,8;
		이론BASIS,ibasis,ibasis,long,8;
		근월물종목코드,gmfutcode,gmfutcode,char,8;
		행사가,actprice,actprice,long,8;
		기초자산단축코드,shcode,shcode,char,6;
		기초자산한글명,basehname,basehname,char,20;
		기초자산현재가,baseprice,baseprice,long,8;
		기초자산현재가대비구분,basesign,basesign,char,1;
		기초자산현재가전일대비,basechange,basechange,long,8;
		기초자산등락률,basediff,basediff,float,6.2;
		기초자산거래량,basevol,basevol,long,12;
		기초자산전일거래량,baseprevol,baseprevol,long,12;
		기초자산매수호가,basebidprc,basebidprc,long,9;
		기초자산매도호가,baseaskprc,baseaskprc,long,9;
		기초자산외국계회원사순매수,basefornetbid,basefornetbid,long,12;
		상품군,prodgrp,prodgrp,char,20;
		승수,mulcnt,mulcnt,float,12.8;
		단일가호가여부,danhochk,danhochk,char,1;
		예상체결가,yeprice,yeprice,long,8;
		예상체결가전일종가대비구분,jnilysign,jnilysign,char,1;
		예상체결가전일종가대비,jnilychange,jnilychange,long,8;
		예상체결가전일종가등락율,jnilydrate,jnilydrate,float,6.2;
	end
	END_DATA_MAP
END_FUNCTION_MAP

