BEGIN_FUNCTION_MAP
	.Func,주식종목조회(t8430),t8430,block,headtype=A;
	BEGIN_DATA_MAP
	t8430InBlock,기본입력,input;
	begin
		구분(0:전체1:코스피2:코스닥),gubun,gubun,char,1;
	end
	t8430OutBlock,출력1,output,occurs;
	begin
		종목명,hname,hname,char,20;
		단축코드,shcode,shcode,char,6;
		확장코드,expcode,expcode,char,12;
		ETF구분(1:ETF),etfgubun,etfgubun,char,1;
		상한가,uplmtprice,uplmtprice,long,8;
		하한가,dnlmtprice,dnlmtprice,long,8;
		전일가,jnilclose,jnilclose,long,8;
		주문수량단위,memedan,memedan,char,5;
		기준가,recprice,recprice,long,8;
		구분(1:코스피2:코스닥),gubun,gubun,char,1;
	end
	END_DATA_MAP
END_FUNCTION_MAP

